config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :wine_makers do
    resources :bottles, only:[:new, :create,]
  end

  resources :bottles, only:[:new, :create, :index, :show] do
    resources :reviews, only: [:new, :create, :index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottle.rb
class Bottle < ApplicationRecord
  belongs_to :wine_maker
  validates :name, :description, :year, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :bottle
  validates :rating, :comment, presence: true
end

app/models/wine_maker.rb
class WineMaker < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController

  def index
    @bottles = Bottle.all
  end

  def show
    @bottle = Bottle.find(params[:id])
  end

  def new
    @bottle = Bottle.new
    @wine_maker = WineMaker.new
  end

  def create
    @bottle = Bottle.new(bottle_params)
    if @bottle.save
      redirect_to bottles_path
    else
      render :new
    end
  end


  private

  def bottle_params
    params.require(:bottle).permit(:name, :year, :grapes, :description, :wine_maker_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @bottle = Bottle.find(params[:bottle_id])
    @review = Review.new
  end

  def create
    @bottle = Bottle.find(params[:bottle_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to bottle_path(@bottle)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :bottle_id)
  end
end

app/controllers/wine_makers_controller.rb
class WineMakersController < ApplicationController

def index
  @wine_makers = WineMaker.all
end

def show
  @wine_maker = WineMaker.find(params[:id])
end

def new
  @wine_maker = WineMaker.new
end

def create
  @wine_maker = WineMaker.new(wine_maker_params)
  if @wine_maker.save
    redirect_to wine_makers_path
  else
    render :new
  end
end

private

def wine_maker_params
  params.require(:wine_maker).permit(:name, :country)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/wine_makers_helper.rb
module WineMakersHelper
end

app/views/bottles/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1491924778227-f225b115dd5f?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjF8fHdpbmV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  Wine favorites
</div>

<div class="container d-flex">
<div class="add-bottle">
<h2> <%= link_to 'Add a bottle', new_bottle_path, class: "wine-button"%>
<h2> <%= link_to 'Add a wine maker', new_wine_maker_path, class: "wine-button"%>
</div>
<div class="wine-container">
<%@bottles.each do |bottle|%>

<div class="wine-bottle">
  <div class="wine-img-review">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
      <div class="infos">
        <h2><%= link_to bottle.name, bottle_path(bottle) %></h2>
        <p><%= bottle.wine_maker.name%> <strong><%=bottle.wine_maker.country%></strong></p>
      </div>
      <div class="add-review">
        <h2> <%= link_to 'Add a review', new_bottle_review_path(bottle), class: "wine-button"%>
      </div>
  </div>
</div>

<%end%>
</div>
</div>

app/views/bottles/new.html.erb
<div class="container">


<%= simple_form_for [ @bottle] do |f| %>
  <%= f.input :name %>
  <%= f.input :year %>
  <%= f.input :grapes %>
  <%= f.input :description %>
  <%= f.association :wine_maker %>
  <%= f.submit "Add this bottle", class: "btn btn-primary" %>
<% end %>

</div>

app/views/bottles/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?ixid=MXwxMjA3fDB8MHxzZWFyY2h8N3x8d2luZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  <%=@bottle.name%>
</div>


<div class="wine-card">
  <div class="card-product-infos">
    <h2><%= @bottle.name%></h2>
    <p><%= @bottle.wine_maker.name%> <strong><%=@bottle.wine_maker.country%></strong></p>
  </div>
</div>

app/views/bottles/test.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1491924778227-f225b115dd5f?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjF8fHdpbmV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  Wine favorites
</div>



<div class="wine-container">
<%@bottles.each do |bottle|%>

<div class="wine-bottle">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="wine-bottle-infos">
    <h2><%= link_to bottle.name, bottle_path(bottle) %></h2>
    <p><%= bottle.wine_maker.name%> <strong><%=bottle.wine_maker.country%></strong></p>
  </div>
</div>

<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WineApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">


<%= simple_form_for [@bottle, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.association :bottle %>
  <%= f.submit "Add a review for this bottle", class: "btn btn-primary" %>
<% end %>

</div>

app/views/wine_makers/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1491924778227-f225b115dd5f?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjF8fHdpbmV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  Wine maker favorites
</div>


<div class="container d-flex">
<div class="add-bottle">
<h2> <%= link_to 'Add a wine maker', new_wine_maker_path%>
</div>
<div class="wine-container">
<%@wine_makers.each do |wine_maker|%>

<div class="wine-bottle">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="wine-bottle-infos">
    <h2><%= link_to wine_maker.name, wine_maker_path(wine_maker) %></h2>
    <p><em><%= wine_maker.country%></em></p>
  </div>
</div>

<%end%>
</div>
</div>

app/views/wine_makers/new.html.erb
<div class="container">


<%= simple_form_for [ @wine_maker] do |f| %>
  <%= f.input :name %>
  <%= f.input :country, as: :string %>
  <%= f.submit "Add this wine maker", class: "btn btn-primary" %>
<% end %>

</div>

app/views/wine_makers/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?ixid=MXwxMjA3fDB8MHxzZWFyY2h8N3x8d2luZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  <%=@wine_maker.name%>
</div>


<div class="wine-card">
  <div class="card-product-infos">
    <h2><%= @wine_maker.name%></h2>
  </div>
</div>